#!/bin/bash

if [ "$1" == "install" ]; then
	cmds="up down logs scale ps"
	for c in $cmds; do
		sudo ln -s /usr/local/bin/dc /usr/local/bin/${c}
	done
	echo "dc: $cmds commands installed!"
	exit 0
fi

file=""
if [ -z "${COMPOSE_FILE:-}" ]; then
	if [ ! -e docker-compose.yml ];  then
		file="-f -"
	fi
fi
project=""
if [ -z "${COMPOSE_PROJECT_NAME:-}" ]; then
	label=$(cat docker-compose.yml |& grep "com.docker.compose.project" | head -1 | sed 's/^.*- com.docker.compose.project=\(.*\)$/\1/')
	if [ $(echo $label | wc -l) -gt 1 ]; then
		project="-p ${label}"
	fi
fi

cmd=""
if [ $(basename $0) == "dc" ]; then
	cmd=$1
	shift
else
	cmd=$(basename $0)
fi

docker-compose $file $project $cmd $@

