#!/bin/bash

name=${1:-}

c=$(docker container ls --format='{{ .Names }}' --filter name=${name})
if [ $(echo "$c" | wc -l) -ne 1 ]; then
	echo "The container ${name} can not be found" >&2
	exit 1
else
	echo -n "Stopped "
	docker container stop $c
	echo -n "Removed "
	docker container rm $c
fi
